import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import "./globals.css";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ReactNode } from "react";

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  try {
    // Fetch session on the server side
    const session = await getServerSession();

    return (
      <html lang="en">
        <body className={inter.className}>
          
     
          {/* Wrapping children with SessionProvider to manage session */}
          <SessionProvider session={session}>{children}</SessionProvider>
         
        </body>
      </html>
    );
  } catch (error) {
    console.error("Error fetching session:", error);
    return (
      <html lang="en">
        <body className={inter.className}>
          
          <SessionProvider session={null}>{children}</SessionProvider>
         
        </body>
      </html>
    );
  }
}